### ISSUE TITLE
Remote audio stops playing after a few minutes

### ISSUE THREAD

**Issue by robertiagar** [atom/electron-quick-start#35]
I'm trying to create a Podcast Manager using Electron (you can find it [here](https://github.com/robertiagar/podcasts) - it's pretty bare for now though)

I've manged to get far ahead to test the playback, but I've noticed that on long podcasts (about 1h long) the playback stops after a few minutes, with no way to recover except an app restart / page refresh.

No errors are shown in the console. Not sure what to do. I know that this is a bug / security feature in Chromium something about serving audio from the same domain as the app, but this node.js is a bit new to me and it's hard for me to wrap my head around it.

Can you give some tips on how to fix this?

I have found the [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=158245) in Chromium. It appears that this bug is still present. Is there a way to work around this?

This has been copied over from [discus](https://discuss.atom.io/t/remote-audio-stops-playing-after-a-few-minutes-help/26120).

Sorry but there was no answer provided there...

**Comment by jlord** [comment]
> I know that this is a bug / security feature in Chromium

If something comes from Chromium there isn't much we can do about it until it is fixed there. Hopefully it will get resolved soon and the fix will become a part of Electron when that version of Chromium is incorporated.

I personally don't know about this issue and cannot offer advice other than to keep an eye on the forum which is where things like this are discussed.

It may be worth checking out [mafintosh/playback](https://github.com/mafintosh/playback) to see if there is anything you can learn from there.

I'm going to close this out here since it's not related to this repository. Good luck!
